// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xkpugyqgytarwqkpkdnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcHVneXFneXRhcndxa3BrZG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0NzczNzAsImV4cCI6MjA4OTA1MzM3MH0.brqUD0KoYvxn1Kc58YXGWKvDGvxaPk723v3lIwBeFSY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);